
/*
 * Filename: swc_system.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component for incrementing age of all signals. This is done for debugging and diagnosis of the signals
 */

#ifndef _H_DEFINE_SWC_SYSTEM
#define _H_DEFINE_SWC_SYSTEM

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_SYSTEM_INCLUDES */

/* USER CODE END SWC_SYSTEM_INCLUDES */



/* USER CODE START SWC_SYSTEM_USERDEFINITIONS */

/* USER CODE END SWC_SYSTEM_USERDEFINITIONS */


/*
 * component: swc_system
 * cycletime: 1
 * description: Runnable for incrementing age of all signals. This is done for debugging and diagnosis of the signals
 * events: 
 * name: SYSTEM_incAge_run
 * shortname: incAge
 * signalIN: so_joystick|so_engine_speed|so_rgb_led|so_brakeLight
 * signalOUT: so_joystick|so_engine_speed|so_rgb_led|so_brakeLight
 * task: tsk_system
 */
void SYSTEM_incAge_run(RTE_event ev);


#endif