/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Set the rgb led brightness based on the engine speed
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"



/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable to create PWM signals based on engine speed
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_engine_speed
 * signalOUT: so_rgb_led
 * task: tsk_realtime
 */
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */
    
    WD_Alive(2);
    
    SC_SPEED_data_t engine_speed;
    SC_PWM_data_t PWM_value;
    
    if(SO_ENGINE_SPEED_signal.age>100) //the age of the signal should not be more than 100ms
    {
      engine_speed.value=0;
    }
    else
    {
       engine_speed = RTE_SC_SPEED_get(&SO_ENGINE_SPEED_signal);  
    }
    
    PWM_value.duty_cycle= engine_speed.value;
    
    RTE_SC_PWM_set(&SO_RGB_LED_signal,PWM_value);
    RTE_SC_PWM_pushPort(&SO_RGB_LED_signal); //write the pwm value to the driver
    
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

