
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: The common global signal pool. All signals will be stored here
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */
#include <stdlib.h>
#include "watchdog.h"
/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_joystick.h"
#include "sc_speed.h"
#include "sc_pwm.h"
#include "sc_brakelight.h"



/*
 * description: Joystick x,y cordinates to calculate the engine speed
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: 0
 * resource: None
 * shortname: joystick
 * signalclass: sc_joystick
 * signalpool: sp_common
 */
extern SC_JOYSTICK_t SO_JOYSTICK_signal;


/*
 * description: speed calculated from the Joystick x,y input commands
 * indriver: 0
 * name: so_engine_speed
 * onDataError: 0
 * onDataUpdate: ev_engine_speed_onData
 * outdriver: 0
 * resource: None
 * shortname: engine_speed
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_ENGINE_SPEED_signal;


/*
 * description: PWM signal output from run_setspeed
 * indriver: 0
 * name: so_rgb_led
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: rgb_led
 * signalclass: sc_pwm
 * signalpool: sp_common
 */
extern SC_PWM_t SO_RGB_LED_signal;


/*
 * description: Brakelight represented based on the engine speed
 * indriver: 0
 * name: so_brakeLight
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: brakeLight
 * signalclass: sc_brakelight
 * signalpool: sp_common
 */
extern SC_BRAKELIGHT_t SO_BRAKELIGHT_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common();

#endif