
/*
 * Filename: sc_controlout_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Signalclass for output data from the control runnable. Which consists of the data of min and hour widget 
 */

#ifndef _H_DEFINE_SC_CONTROLOUT_TYPE
#define _H_DEFINE_SC_CONTROLOUT_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_CONTROLOUT_INCLUDES */

/* USER CODE END SC_CONTROLOUT_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_CONTROLOUT signal    
 **********************************************************************/

/* USER CODE START SC_CONTROLOUT_USERDEFINITIONS */

typedef struct{
   uint8_t m_Hour;
   uint8_t m_Min;  
}CLOCK_time_t;

#define SC_Clock_Time_INIT_DATA ((CLOCK_time_t){0,0}) 

typedef enum{
   CLOCK_MODE_DISPLAYING,
   CLOCK_MODE_EDITING_HOUR,
   CLOCK_MODE_EDITING_MINUTE 
}CLOCK_Mode;

/* USER CODE END SC_CONTROLOUT_USERDEFINITIONS */

typedef 
/* USER CODE START SC_CONTROLOUT_SIGNALDATADEFINITION */
struct
{
	CLOCK_time_t Time_data;
    CLOCK_Mode Mode;
} 
/* USER CODE END SC_CONTROLOUT_SIGNALDATADEFINITION */
SC_CONTROLOUT_data_t;

/* USER CODE START InitSC_CONTROLOUT */
#define SC_CONTROLOUT_INIT_DATA ((SC_CONTROLOUT_data_t){{0,0},CLOCK_MODE_DISPLAYING})
/* USER CODE END InitSC_CONTROLOUT */





/* USER CODE START SC_CONTROLOUT_USERFUNCTIONS */

/* USER CODE END SC_CONTROLOUT_USERFUNCTIONS */


#endif