/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: The common global signal pool. All signals will be stored here
 * endaddr: ADR_SP_COMMON_END
 * name: sp_common
 * shortname: common
 * startaddr: ADR_SP_COMMON_START
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_joystick.h"
#include "sc_joystick_type.h"
#include "sc_speed.h"
#include "sc_speed_type.h"
#include "sc_pwm.h"
#include "sc_pwm_type.h"
#include "sc_brakelight.h"
#include "sc_brakelight_type.h"



/* signal configuration */
/*
 * description: Joystick x,y cordinates to calculate the engine speed
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: 0
 * resource: None
 * shortname: joystick
 * signalclass: sc_joystick
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_joystick_updTasks = { tsk_realtime };
 

static const SC_JOYSTICK_cfg_t SO_JOYSTICK_cfg = 
{
   /* indriver           */  SC_JOYSTICK_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  ev_joystick_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_joystick_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_joystick */


/* signal data */

SC_JOYSTICK_t SO_JOYSTICK_signal= 
{
   /* init value    */  SC_JOYSTICK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_JOYSTICK_cfg,
}; /* data so_joystick */

/* signal configuration */
/*
 * description: speed calculated from the Joystick x,y input commands
 * indriver: 0
 * name: so_engine_speed
 * onDataError: 0
 * onDataUpdate: ev_engine_speed_onData
 * outdriver: 0
 * resource: None
 * shortname: engine_speed
 * signalclass: sc_speed
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_engine_speed_updTasks = { tsk_realtime };
 

static const SC_SPEED_cfg_t SO_ENGINE_SPEED_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_engine_speed_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_engine_speed_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_engine_speed */


/* signal data */

SC_SPEED_t SO_ENGINE_SPEED_signal= 
{
   /* init value    */  SC_SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_ENGINE_SPEED_cfg,
}; /* data so_engine_speed */

/* signal configuration */
/*
 * description: PWM signal output from run_setspeed
 * indriver: 0
 * name: so_rgb_led
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: rgb_led
 * signalclass: sc_pwm
 * signalpool: sp_common
 */

 

static const SC_PWM_cfg_t SO_RGB_LED_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_PWM_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_rgb_led */


/* signal data */

SC_PWM_t SO_RGB_LED_signal= 
{
   /* init value    */  SC_PWM_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_RGB_LED_cfg,
}; /* data so_rgb_led */

/* signal configuration */
/*
 * description: Brakelight represented based on the engine speed
 * indriver: 0
 * name: so_brakeLight
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: brakeLight
 * signalclass: sc_brakelight
 * signalpool: sp_common
 */

 

static const SC_BRAKELIGHT_cfg_t SO_BRAKELIGHT_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_BRAKELIGHT_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_brakelight */


/* signal data */

SC_BRAKELIGHT_t SO_BRAKELIGHT_signal= 
{
   /* init value    */  SC_BRAKELIGHT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_BRAKELIGHT_cfg,
}; /* data so_brakelight */



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_JOYSTICK_incAge( &SO_JOYSTICK_signal, tick); 
   RTE_SC_SPEED_incAge( &SO_ENGINE_SPEED_signal, tick); 
   RTE_SC_PWM_incAge( &SO_RGB_LED_signal, tick); 
   RTE_SC_BRAKELIGHT_incAge( &SO_BRAKELIGHT_signal, tick); 
   
}

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common(){
   RTE_SC_JOYSTICK_init( &SO_JOYSTICK_signal); 
   RTE_SC_SPEED_init( &SO_ENGINE_SPEED_signal); 
   RTE_SC_PWM_init( &SO_RGB_LED_signal); 
   RTE_SC_BRAKELIGHT_init( &SO_BRAKELIGHT_signal); 
   
}		


