/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "A_7_Seg_1_aliases.h"
#include "A_7_Seg_1.h"
#include "B_7_Seg_1_aliases.h"
#include "B_7_Seg_1.h"
#include "C_7_Seg_1_aliases.h"
#include "C_7_Seg_1.h"
#include "D_7_Seg_1_aliases.h"
#include "D_7_Seg_1.h"
#include "E_7_Seg_1_aliases.h"
#include "E_7_Seg_1.h"
#include "F_7_Seg_1_aliases.h"
#include "F_7_Seg_1.h"
#include "G_7_Seg_1_aliases.h"
#include "G_7_Seg_1.h"
#include "DP_7_Seg_1_aliases.h"
#include "DP_7_Seg_1.h"
#include "isr_button.h"
#include "Button_1_aliases.h"
#include "Button_1.h"
#include "Sel_A_7_Seg_aliases.h"
#include "Sel_A_7_Seg.h"
#include "Control_Reg_1.h"
#include "UART_1.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "RGB_R_aliases.h"
#include "RGB_R.h"
#include "Button_2_aliases.h"
#include "Button_2.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "RGB_Y_aliases.h"
#include "RGB_Y.h"
#include "led_rgb_r_aliases.h"
#include "led_rgb_r.h"
#include "led_rgb_g_aliases.h"
#include "led_rgb_g.h"
#include "led_rgb_b_aliases.h"
#include "led_rgb_b.h"
#include "PWM_led_red.h"
#include "PWM_led_green.h"
#include "PWM_led_yellow.h"
#include "Clock_1.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

