/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component for Statemachine logic and send data on min and hour widgets
 * name: swc_Control
 * shortname: Control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"



/* USER CODE START SWC_CONTROL_INCLUDE */
#include "statemachine_cfg.h"
#include "statemachine.h"
#include <stdlib.h>
/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"


/* USER CODE START SWC_CONTROL_USERDEFINITIONS */


/*****************************************************************************/
/* Local function prototypes ('static')                                      */
/*****************************************************************************/
static void  dispatch_KeyleftWdgHours();
static void  dispatch_KeyleftWdgToMinutes();
static void  dispatch_KeyRightWdgToHours();
static void  dispatch_RightLongPressWdgToHours();
static void  dispatch_250msWdgToHours();
static void  dispatch_250msWdgToHours();
static void  dispatch_KeyleftWdgToDisplaying();
static void  dispatch_KeyRightWdgToMinutes();
static void  dispatch_RightLongPressWdgToMinutes();
static void  dispatch_250msWdgToMinutes();
static void  CLOCK_updateTime();
static void  CLOCK_updateDisplay();
static void  CLOCK_updateDisplayHour();
static void  CLOCK_updateDisplayMin();

static void CLOCK_IncrementHours();
static void CLOCK_IncrementMinutes();



/** ---------------------------------- Transitions ---------------------------------------- **/

/**  ===== IS_Displaying ====   */
static const STATE_stateInnerTransitionTable_t IS_Displaying_Transitions = {
/*    Event                 ToState                 Guard                       Action                       */
    { EV_KeyLeft,           IS_ContainerHour,           0,           dispatch_KeyleftWdgHours}, 
    { EV_1MIN,               IS_Displaying,              0,                  CLOCK_updateTime},
};

/**  ===== IS_ContainerHour ====   */
static const STATE_stateInnerTransitionTable_t IS_ContainerHour_Transitions = {
/*    Event                 ToState                 Guard                       Action                       */
    { EV_KeyLeft,           IS_ContainerMin,            0,                      dispatch_KeyleftWdgToMinutes}, 
    { EV_KeyRight,          IS_ContainerHour,           0,                      dispatch_KeyRightWdgToHours},
    { EV_RightLongPress,          IS_ContainerHour,           0,                dispatch_RightLongPressWdgToHours},
    { EV_250ms,          IS_ContainerHour,           0,                         dispatch_250msWdgToHours}, 
};

/**  ===== IS_ContainerMin ====   */
static const STATE_stateInnerTransitionTable_t IS_ContainerMin_Transitions = {
/*    Event                 ToState                 Guard                       Action                       */
    { EV_KeyLeft,           IS_Displaying,            0,                        dispatch_KeyleftWdgToDisplaying}, 
    { EV_KeyRight,          IS_ContainerMin,           0,                      dispatch_KeyRightWdgToMinutes},
    { EV_RightLongPress,          IS_ContainerMin,           0,                dispatch_RightLongPressWdgToMinutes},
    { EV_250ms,          IS_ContainerMin,           0,                         dispatch_250msWdgToMinutes}, 
};


static const STATE_stateOuterTransitionTable_t ContainerStateMachine_Transitions = {
/*    fromState                  Pointer to table                            Size of table [Elements]    */
    { IS_Displaying,          &IS_Displaying_Transitions,              sizeof(IS_Displaying_Transitions)/sizeof(STATE_stateInnerTransition_t)    },
    { IS_ContainerHour,     &IS_ContainerHour_Transitions,         sizeof(IS_ContainerHour_Transitions)/sizeof(STATE_stateInnerTransition_t)     },
    { IS_ContainerMin,     &IS_ContainerMin_Transitions,         sizeof(IS_ContainerMin_Transitions)/sizeof(STATE_stateInnerTransition_t) },
};
static const uint16_t ContainerStateMachine_Transitions_size = sizeof(ContainerStateMachine_Transitions)/sizeof(STATE_stateOuterTransition_t);

/** ---------------------------------- Action ------------------------------------------- **/

static const STATE_stateActionTable_t ContainerStateMachine_StateActions = {
/*  fromState               Entry                    Exit    */
  { IS_Displaying,          CLOCK_updateDisplay,      0   },
  { IS_ContainerHour,       0,                        0   }, 
  { IS_ContainerMin,        0,                       0   },
};
static const uint16_t ContainerStateMachine_StateActions_size = sizeof(ContainerStateMachine_StateActions)/sizeof(STATE_stateAction_t);

/******************************************************** Child State Machines Start ************************************************************/

/******************************************************** IsEditing Hour State Machine Start************************************************************/


/**  ===== IS_Displaying ====   */
static const STATE_stateInnerTransitionTable_t HourFocus_Transitions = {
/*    Event                 ToState                 Guard                       Action                       */
    { EV_KeyLeft,           MinFocus,               0,                           0}, 
    { EV_KeyRight,          HourFocus,              0,                           CLOCK_IncrementHours},
    { EV_RightLongPress,    HourAutoInc,            0,                           CLOCK_IncrementHours},
};

/**  ===== IS_ContainerHour ====   */
static const STATE_stateInnerTransitionTable_t HourAutoInc_Transitions = {
/*    Event                 ToState                 Guard                     Action                       */
    { EV_KeyRight,          HourFocus,              0,                         0},
    { EV_250ms,             HourAutoInc,            0,                         CLOCK_IncrementHours}, 
};


static const STATE_stateOuterTransitionTable_t HourStateMachine_Transitions = {
/*    fromState                  Pointer to table                            Size of table [Elements]    */
    { HourFocus,          &HourFocus_Transitions,              sizeof(HourFocus_Transitions)/sizeof(STATE_stateInnerTransition_t)    },
    { HourAutoInc,     &HourAutoInc_Transitions,         sizeof(HourAutoInc_Transitions)/sizeof(STATE_stateInnerTransition_t)     },
};
static const uint16_t HourStateMachine_Transitions_size = sizeof(HourStateMachine_Transitions)/sizeof(STATE_stateOuterTransition_t);

/** ---------------------------------- Action ------------------------------------------- **/

static const STATE_stateActionTable_t HourStateMachine_StateActions = {
/*  fromState               Entry                                    Exit    */
  { HourFocus,              CLOCK_updateDisplayHour,                     0   },
  { HourAutoInc,            CLOCK_updateDisplayHour,                     0   },
};
static const uint16_t HourStateMachine_StateActions_size = sizeof(HourStateMachine_StateActions)/sizeof(STATE_stateAction_t);

/******************************************************** IsEditing Hour State Machine end************************************************************/


/******************************************************** IsEditing Min State Machine Start************************************************************/


/**  ===== IS_Displaying ====   */
static const STATE_stateInnerTransitionTable_t MinFocus_Transitions = {
/*    Event                 ToState                 Guard                       Action                       */
    { EV_KeyLeft,           IS_Displaying,               0,                           0}, 
    { EV_KeyRight,          MinFocus,              0,                           CLOCK_IncrementMinutes},
    { EV_RightLongPress,    MinAutoInc,            0,                           CLOCK_IncrementMinutes},
};

/**  ===== IS_ContainerHour ====   */
static const STATE_stateInnerTransitionTable_t MinAutoInc_Transitions = {
/*    Event                 ToState                 Guard                     Action                       */
    { EV_KeyRight,          MinFocus,              0,                         0},
    { EV_250ms,             MinAutoInc,            0,                         CLOCK_IncrementMinutes}, 
};


static const STATE_stateOuterTransitionTable_t MinStateMachine_Transitions = {
/*    fromState                  Pointer to table                            Size of table [Elements]    */
    { MinFocus,          &MinFocus_Transitions,              sizeof(MinFocus_Transitions)/sizeof(STATE_stateInnerTransition_t)    },
    { MinAutoInc,     &MinAutoInc_Transitions,         sizeof(MinAutoInc_Transitions)/sizeof(STATE_stateInnerTransition_t)     },
};
static const uint16_t MinStateMachine_Transitions_size = sizeof(MinStateMachine_Transitions)/sizeof(STATE_stateOuterTransition_t);

/** ---------------------------------- Action ------------------------------------------- **/

static const STATE_stateActionTable_t MinStateMachine_StateActions = {
/*  fromState               Entry                                    Exit    */
  { MinFocus,              CLOCK_updateDisplayMin,                     0   }, 
  { MinAutoInc,            CLOCK_updateDisplayMin,                     0   },
};
static const uint16_t MinStateMachine_StateActions_size = sizeof(MinStateMachine_StateActions)/sizeof(STATE_stateAction_t);

/******************************************************** IsEditing Min State Machine end************************************************************/

/********************************************************* Child State Machines end*********************************************************************/


static ActiveObject_t Container_ao= { {&ContainerStateMachine_Transitions, &ContainerStateMachine_Transitions_size,
    &ContainerStateMachine_StateActions, &ContainerStateMachine_StateActions_size, ContainerStateMachine_INIT_DATA} };

static ActiveObject_t Hour_ao = {{ &HourStateMachine_Transitions, &HourStateMachine_Transitions_size,
    &HourStateMachine_StateActions, &HourStateMachine_StateActions_size, HourStateMachine_INIT_DATA} };

static ActiveObject_t Min_ao = {{&MinStateMachine_Transitions, &MinStateMachine_Transitions_size,
    &MinStateMachine_StateActions, &MinStateMachine_StateActions_size, MinStateMachine_INIT_DATA} };

CLOCK_time_t CLOCK_Time = SC_Clock_Time_INIT_DATA;


//FSM_t Container_FSM = {&ContainerStateMachine_Transitions, &ContainerStateMachine_Transitions_size,
//    &ContainerStateMachine_StateActions, &ContainerStateMachine_StateActions_size, ContainerStateMachine_INIT_DATA};
//
//FSM_t Hour_FSM = { &HourStateMachine_Transitions, &HourStateMachine_Transitions_size,
//    &HourStateMachine_StateActions, &HourStateMachine_StateActions_size, HourStateMachine_INIT_DATA};
//
//FSM_t Min_FSM = {&MinStateMachine_Transitions, &MinStateMachine_Transitions_size,
//    &MinStateMachine_StateActions, &MinStateMachine_StateActions_size, MinStateMachine_INIT_DATA};

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_Control
 * cycletime: 0
 * description: Runnable for Statemachine logic and send data on min and hour widgets
 * events: ev_Button_OnData
 * name: CONTROL_Clock_control_run
 * shortname: Clock_control
 * signalIN: so_ButtonEvent
 * signalOUT: so_ControlOut
 * task: tsk_realtime
 */
void CONTROL_Clock_control_run(RTE_event ev){
	
	/* USER CODE START CONTROL_Clock_control_run */
        
   
        SC_BUTTONEVENT_data_t eventvalue;   
        eventvalue= RTE_SC_BUTTONEVENT_get(&SO_BUTTONEVENT_signal);
    
    if(eventvalue.m_ev!= EV_NULL)
    {

    
    STATE_processEvent(*Container_ao.StateMachine.OuterTransitionTable,
                       *Container_ao.StateMachine.OuterTransitionTableSize,
                       *Container_ao.StateMachine.actionTable, 
                        *Container_ao.StateMachine.actionTableSize,
                        eventvalue.m_ev,
                        &Container_ao.StateMachine.state);
    }
    
    
    /* USER CODE END CONTROL_Clock_control_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */


/*****************************************************************************/
/* Local type definitions ('typedef')                                        */
/*****************************************************************************/


/*****************************************************************************/
/* Local variable definitions ('static')                                     */
/*****************************************************************************/




/*****************************************************************************/
/* Function implementation - global ('extern') and local ('static')          */
/*****************************************************************************/
void CONTROL_init_run()
{

  STATE_initState(   *Container_ao.StateMachine.actionTable, 
                        *Container_ao.StateMachine.actionTableSize,
                        &Container_ao.StateMachine.state);  
}

static void dispatch_KeyleftWdgHours()
{
    
    
    //UART_LOG_PutString("dispatch_KeyleftWdgHours - Hour Focus \r");
    
    
    ChildSTATE_initState(   *Hour_ao.StateMachine.actionTable, 
                        *Hour_ao.StateMachine.actionTableSize,
                        &Hour_ao.StateMachine.state, HourStateMachine_INIT_DATA);
    
    
}
static void  dispatch_KeyleftWdgToMinutes()
{
    //UART_LOG_PutString("dispatch_KeyleftWdgToMinutes - Min Focus \r");
    
    ChildSTATE_initState(   *Min_ao.StateMachine.actionTable, 
                        *Min_ao.StateMachine.actionTableSize,
                        &Min_ao.StateMachine.state, MinStateMachine_INIT_DATA);    
    
}
static void  dispatch_KeyRightWdgToHours()
{
    //UART_LOG_PutString("dispatch_KeyRightWdgToHours - Hour Focus \r");

    STATE_processEvent(*Hour_ao.StateMachine.OuterTransitionTable,
                       *Hour_ao.StateMachine.OuterTransitionTableSize,
                        *Hour_ao.StateMachine.actionTable, 
                        *Hour_ao.StateMachine.actionTableSize,
                        EV_KeyRight,
                        &Hour_ao.StateMachine.state); 
    
    
}
static void  dispatch_RightLongPressWdgToHours()
{
    //UART_LOG_PutString("dispatch_RightLongPressWdgToHours - Hour Auto Increment \r");
    STATE_processEvent(*Hour_ao.StateMachine.OuterTransitionTable,
                       *Hour_ao.StateMachine.OuterTransitionTableSize,
                        *Hour_ao.StateMachine.actionTable, 
                        *Hour_ao.StateMachine.actionTableSize,
                        EV_RightLongPress,
                        &Hour_ao.StateMachine.state); 
    
    
}
static void  dispatch_250msWdgToHours()
{

        STATE_processEvent(*Hour_ao.StateMachine.OuterTransitionTable,
                       *Hour_ao.StateMachine.OuterTransitionTableSize,
                        *Hour_ao.StateMachine.actionTable, 
                        *Hour_ao.StateMachine.actionTableSize,
                        EV_250ms,
                       &Hour_ao.StateMachine.state);
    
    
}
static void  dispatch_KeyleftWdgToDisplaying()
{
    //UART_LOG_PutString("dispatch_KeyleftWdgToDisplaying - IS Displaying \r");
            STATE_processEvent(*Min_ao.StateMachine.OuterTransitionTable,
                       *Min_ao.StateMachine.OuterTransitionTableSize,
                        *Min_ao.StateMachine.actionTable, 
                        *Min_ao.StateMachine.actionTableSize,
                        EV_KeyLeft,
                        &Min_ao.StateMachine.state); 
            
    
}
static void  dispatch_KeyRightWdgToMinutes()
{
    //UART_LOG_PutString("dispatch_KeyRightWdgToMinutes - Min Focus \r");
        STATE_processEvent(*Min_ao.StateMachine.OuterTransitionTable,
                       *Min_ao.StateMachine.OuterTransitionTableSize,
                        *Min_ao.StateMachine.actionTable, 
                        *Min_ao.StateMachine.actionTableSize,
                        EV_KeyRight,
                        &Min_ao.StateMachine.state); 
       
    
}
static void  dispatch_RightLongPressWdgToMinutes()
{
    //UART_LOG_PutString("dispatch_RightLongPressWdgToMinutes - Min Auto Increment \r");
    
        STATE_processEvent(*Min_ao.StateMachine.OuterTransitionTable,
                       *Min_ao.StateMachine.OuterTransitionTableSize,
                        *Min_ao.StateMachine.actionTable, 
                        *Min_ao.StateMachine.actionTableSize,
                        EV_RightLongPress,
                        &Min_ao.StateMachine.state);   
    
}
static void  dispatch_250msWdgToMinutes()
{
        STATE_processEvent(*Min_ao.StateMachine.OuterTransitionTable,
                       *Min_ao.StateMachine.OuterTransitionTableSize,
                        *Min_ao.StateMachine.actionTable, 
                        *Min_ao.StateMachine.actionTableSize,
                        EV_250ms,
                        &Min_ao.StateMachine.state);
    
}
static void  CLOCK_updateTime()
{
    //UART_LOG_PutString("CLOCK_updateTime \r");

    CLOCK_IncrementMinutes();
    
    
}
static void  CLOCK_updateDisplay()
{   
   SC_CONTROLOUT_data_t value;
    value.Time_data = CLOCK_Time;
    value.Mode= CLOCK_MODE_DISPLAYING;
    RTE_SC_CONTROLOUT_set(&SO_CONTROLOUT_signal, value);
   
}

static void  CLOCK_updateDisplayHour()
{
    SC_CONTROLOUT_data_t value;
    value.Time_data = CLOCK_Time;
    value.Mode= CLOCK_MODE_EDITING_HOUR;
    RTE_SC_CONTROLOUT_set(&SO_CONTROLOUT_signal, value);
}
static void  CLOCK_updateDisplayMin()
{
    SC_CONTROLOUT_data_t value;
    value.Time_data = CLOCK_Time;
    value.Mode= CLOCK_MODE_EDITING_MINUTE;
    RTE_SC_CONTROLOUT_set(&SO_CONTROLOUT_signal, value);
    
}

static void CLOCK_IncrementHours()
{
    //UART_LOG_PutString("CLOCK_IncrementHours \r");
    if(CLOCK_Time.m_Hour < 24)
    {
       CLOCK_Time.m_Hour++; 
    }
    if(CLOCK_Time.m_Hour == 24)
    {
      CLOCK_Time.m_Hour=0;  
    }
}

static void CLOCK_IncrementMinutes()
{
    //UART_LOG_PutString("CLOCK_IncrementMinutes \r");
    if(CLOCK_Time.m_Min < 60)
    {
        CLOCK_Time.m_Min++;
       
    }
    if(CLOCK_Time.m_Min == 60)
    {
       CLOCK_Time.m_Min =0; 
       CLOCK_IncrementHours(); 
    }
}

/* USER CODE END SWC_CONTROL_FUNCTIONS */

