
/*
 * Filename: swc_display.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component for TFT data display
 */

#ifndef _H_DEFINE_SWC_DISPLAY
#define _H_DEFINE_SWC_DISPLAY

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_DISPLAY_INCLUDES */

/* USER CODE END SWC_DISPLAY_INCLUDES */



/* USER CODE START SWC_DISPLAY_USERDEFINITIONS */

/* USER CODE END SWC_DISPLAY_USERDEFINITIONS */


/*
 * component: swc_Display
 * cycletime: 250
 * description: Runnable for TFT data display
 * events: 
 * name: DISPLAY_Clock_display_run
 * shortname: Clock_display
 * signalIN: so_ControlOut
 * signalOUT: so_Display
 * task: tsk_hmi
 */
void DISPLAY_Clock_display_run(RTE_event ev);


#endif