
/*
 * Filename: tsk_hmi.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Task for TFT display long runnable
 */

#ifndef _H_DEFINE_TSK_HMI
#define _H_DEFINE_TSK_HMI

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_HMI_INCLUDES */

/* USER CODE END TSK_HMI_INCLUDES */



/*
 * description: Task for TFT display long runnable
 * events: 
 * mode: Cyclic
 * name: tsk_hmi
 * shortname: hmi
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 */
DeclareTask(tsk_hmi);

/* USER CODE START TSK_HMI_TASKUSERFUNCTION */

/* USER CODE END TSK_HMI_TASKUSERFUNCTION */


#endif