
/*
 * Filename: swc_brake.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Set the red led based on the engine speed
 */

#ifndef _H_DEFINE_SWC_BRAKE
#define _H_DEFINE_SWC_BRAKE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_BRAKE_INCLUDES */

/* USER CODE END SWC_BRAKE_INCLUDES */



/* USER CODE START SWC_BRAKE_USERDEFINITIONS */

/* USER CODE END SWC_BRAKE_USERDEFINITIONS */


/*
 * component: swc_brake
 * cycletime: 0
 * description: Runnable to create brakelight signal for led red
 * events: ev_engine_speed_onData
 * name: BRAKE_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_engine_speed
 * signalOUT: so_brakeLight
 * task: tsk_realtime
 */
void BRAKE_setBrakeLight_run(RTE_event ev);


#endif