/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Set the rgb led brightness based on the engine speed
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"



/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable to create PWM signals based on engine speed
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_engine_speed
 * signalOUT: so_rgb_led
 * task: tsk_realtime
 */
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */

    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

