
/*
 * Filename: swc_engine.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Set the rgb led brightness based on the engine speed
 */

#ifndef _H_DEFINE_SWC_ENGINE
#define _H_DEFINE_SWC_ENGINE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_ENGINE_INCLUDES */

/* USER CODE END SWC_ENGINE_INCLUDES */



/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */


/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable to create PWM signals based on engine speed
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_engine_speed
 * signalOUT: so_rgb_led
 * task: tsk_realtime
 */
void ENGINE_setEngine_run(RTE_event ev);


#endif